server:
  port: 8083

spring:
  application:
    name: Vaccine

  r2dbc:
    url: r2dbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
    username: postgres.czvijwwwsheijovdvwci
    password: cXZzyYANPji9OE8v


# Propiedades personalizadas - DEBEN estar en el nivel raíz
jwt:
  secret: mySecretKey123456789012345678901234567890 # Debe ser la misma que el servicio de autenticación

auth-service:
  url: https://8085-vallegrandea-mssecurity-oirp2ljshek.ws-us120.gitpod.io
