server:
  port: 8083

spring:
  application:
    name: Vaccine

  r2dbc:
    url: r2dbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
    username: postgres.czvijwwwsheijovdvwci
    password: cXZzyYANPji9OE8v

